FROM node:12
WORKDIR /app

RUN mkdir order-history-service

COPY ./order-history-service/package*.json ./order-history-service

RUN cd ./order-history-service && npm install

COPY order-history-service ./order-history-service
COPY common ./common

CMD [ "node", "order-history-service/index.js" ]