FROM node:12
WORKDIR /app

COPY eventuate-tram-core-nodejs ./eventuate-tram-core-nodejs

#Copy package.json and package-lock.json(if exists) into container
COPY package*.json ./

RUN npm install

COPY order-service ./order-service
COPY common ./common

CMD [ "node", "order-service/index.js" ]