FROM node:12
WORKDIR /app

RUN mkdir order-service

COPY common-module ./common-module

COPY ./order-service/package*.json ./order-service/
COPY ./common-module/package*.json ./common-module/

RUN cd ./common-module && npm install
RUN cd ./order-service && npm install

COPY order-service ./order-service

CMD cd order-service && node index.js
