#!/usr/bin/env bash

export EVENTUATE_COMMON_VERSION=0.8.0.RELEASE
export EVENTUATE_KAFKA_VERSION=0.3.0.RELEASE
export EVENTUATE_CDC_VERSION=0.6.0.RC1
export EVENTUATE_CDC_KAFKA_ENABLE_BATCH_PROCESSING=false